# &#9000; Laboratorio 1 {-}

* <a href="data/mcdonalds.csv" target="_blank">Datos del laboratorio</a>
* <a href="https://www.google.cl" target="_blank">Grabación</a>

Un gerente de McDonald's le ha contratado para realizar un balance sobre la cantidad de grasa saturada que tienen sus alimentos, ya que no están cumpliendo la normativa y necesitan disminuirlas con suma urgencia.

Usted con sus sabios conocimientos sobre esta cadena de comida rápida, cree la cantidad de sodio incide directamente en la cantidad de grasa saturada que tendrán finalmente los alimentos. La base de datos `mcdonalds.csv` contiene dicha información.

1. Realice un análisis exploratorio a través de gráficos que le permita comparar la grasa saturada de los alimentos respecto a la categoría del alimento y el sodio del mismo. ¿Qué características llaman su atención?

2. Construya un gráfico que muestre las correlaciones entre cada variable de la base de datos. Indique los tres pares de variables que tienen una asociación lineal más fuerte.

3. Usando la variable que tenga la asociación lineal más fuerte respecto a la grasa saturada, realice un gráfico de dispersión y añada la mejor recta que se adapte a las observaciones. Comente.

3. Genere un estimador de Nayara-Watson, encuentre el mejor valor del ancho de banda a través de validación cruzada del tipo *leave-one-out*.

4. Ahora, realize una regresión basada en splines usando el package `psplines`. Encuentre el mejor valor de suavizamiento a través de validación cruzada.

5. Grafique las variables involucradas en los dos modelos, incluyendo curvas con los valores ajustados por estos, además añada la recta encontrada en el paso **3**. Decida que tipo de regresión es más apta para el contexto y concluya.
